import type { Metadata } from "next";
import "./globals.css";

import Head from "next/head";
import Script from "next/script";

import { Montserrat } from "next/font/google"

const montserrat = Montserrat({
  weight: ['100', '300', '500'],
  subsets: ['cyrillic'],
  variable: "--font-montserrat"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    
      <Script src="https://aframe.io/releases/1.0.4/aframe.min.js"></Script>
      <Script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></Script>
      <Script src="./scripts/gesture-detector.js"></Script>
      <Script src="./scripts/gesture-handler.js"></Script>
      <body className={`${montserrat.className} ${montserrat.variable}`}>

        {children}

      </body>
    </html>
  );
}
