import type { Metadata } from "next";
import "./globals.css";

import Head from "next/head";

import { Montserrat } from "next/font/google"

const montserrat = Montserrat({
  weight: ['100', '300', '500'],
  subsets: ['cyrillic'],
  variable: "--font-montserrat"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <Head>
        <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
      </Head>
      <body className={`${montserrat.className} ${montserrat.variable}`}>

        {children}

      </body>
    </html>
  );
}
